### PR TITLE
Better icons and links for execs

### PR DESCRIPTION
**Pull request by Nandob777**
Pretty much, I added actual links to the icons under the execs, and changed them to be more relevant. this addresses #27, which I made today

### CODE REVIEW

**Comment by ratstache** [comment]
can you post a screenshot of the logos? Other than that it all looks good

**Comment by ratstache** [comment]
oh also if you put "resolves #27" it will auto close when merging

**Comment by ratstache** [comment]
Just going to throw this over the fence because I'm headed to China and I don't know if github will work there...

**Comment by ratstache** [comment]
Nice, it looks great good work!

**Comment by Nandob777** [comment]
Did not realise "resolves #27" would auto close the issue.  I'll try to keep screenshots in mind in the future

**Pull request merged**
